manifest:
  projects:
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf
      revision: v2.5.0
      import:
        name-allowlist:
          - bsim
          - zephyr
          - cmsis
          - nrfxlib
          - mcuboot
          - mcumgr
          - tinycbor
          - segger
          - tinycrypt
          - hal_nordic
